version: '3.8'

services:
  server:
    image: bhathika/inoweb-server:latest
    ports:
      - "5000:5000"
    volumes:
      - ./server/src/uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/inoweb
    depends_on:
      - mongodb

  client:
    image: bhathika/inoweb-client:latest
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
