version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_container
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app        # Sync local client folder with container /app
      - /app/node_modules    # Exclude node_modules to avoid conflicts
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_container
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/inoweb
    volumes:
      - ./server:/app        # Sync local server folder with container /app
      - /app/node_modules    # Exclude node_modules to avoid conflicts
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
      image: mongo-express
      container_name: mongo_express_container
      restart: always
      ports:
        - "8081:8081"  # Access Mongo Express at localhost:8081
      environment:
        - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
        - ME_CONFIG_BASICAUTH_USERNAME=admin
        - ME_CONFIG_BASICAUTH_PASSWORD=admin


volumes:
  mongo_data:
