version: '3.8'

services:
  server:
    image: bhathika/inoweb-server:1.4
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/inoweb
    depends_on:
      - mongodb
    volumes:
      - ./server/src/uploads/products:/app/src/uploads/products
  client:
    image: bhathika/inoweb-client:1.4
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
