name: Node.js CI/CD with Docker

on:
  push:
    branches: [ CI/CD ]
  pull_request:
    branches: [ CI/CD ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongo localhost:27017/test --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MONGO_URI: mongodb://host.docker.internal:27017/inoweb
      MONGO_URI_TEST: mongodb://host.docker.internal:27017/inoweb_test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set environment variables from secrets
        run: |
          echo "PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}" >> $GITHUB_ENV
          echo "PAYPAL_CLIENT_SECRET=${{ secrets.PAYPAL_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "PAYPAL_MODE=${{ secrets.PAYPAL_MODE }}" >> $GITHUB_ENV
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          echo "MONGO_URI=mongodb://host.docker.internal:27017/inoweb" >> $GITHUB_ENV
          echo "MONGO_URI_TEST=mongodb://host.docker.internal:27017/inoweb_test" >> $GITHUB_ENV

      - name: Set up Node.js for Client
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies in Client
        run: |
          cd client
          npm install

      - name: Run tests in Client
        run: |
          cd client
          npm test

      - name: Set up Node.js for Server
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies in Server
        run: |
          cd server
          npm install

      - name: Run tests in Server
        run: |
          cd server
          npm test

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build Docker Image for Client
        run: docker build -t $DOCKER_USERNAME/inoweb-client:1.4 ./client

      - name: Build Docker Image for Server
        run: docker build -t $DOCKER_USERNAME/inoweb-server:1.4 ./server

      - name: Push Docker Images
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_USERNAME/inoweb-client:1.4
          docker push $DOCKER_USERNAME/inoweb-server:1.4

      - name: Validate Docker Compose
        run: docker-compose -f docker-compose.yml config
